### ISSUE TITLE
Fix All Developer Console Crashes

### ISSUE THREAD

**Issue by torch2424** [torch2424/Stats-Monitor-Widget#15]
Here's the crashes for the latest production in the last 6 months Both From Stats Free:
1. Java.lang.NullPointerException: Attempt to invoke virtual method 'void com.amazon.device.ads.MetricsCollector.stopMetric(com.amazon.device.ads.Metrics$MetricType)' on a null object reference
   at com.amazon.device.ads.AdLoader.finalizeFetchAd(AdLoader.java:383)
   at com.amazon.device.ads.AdLoader$2.run(AdLoader.java:98)
   at android.os.Handler.handleCallback(Handler.java:739)
   at android.os.Handler.dispatchMessage(Handler.java:95)
   at android.os.Looper.loop(Looper.java:211)
   at android.app.ActivityThread.main(ActivityThread.java:5373)
   at java.lang.reflect.Method.invoke(Native Method)
   at java.lang.reflect.Method.invoke(Method.java:372)
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)
2. (Only on galaxy S5?)
   java.lang.RuntimeException: Unable to start receiver com.torch2424.simplemonitor.SmAlarm: java.lang.RuntimeException: system server dead?
   at android.app.ActivityThread.handleReceiver(ActivityThread.java:2955)
   at android.app.ActivityThread.access$1800(ActivityThread.java:172)
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1498)
   at android.os.Handler.dispatchMessage(Handler.java:102)
   at android.os.Looper.loop(Looper.java:145)
   at android.app.ActivityThread.main(ActivityThread.java:5835)
   at java.lang.reflect.Method.invoke(Native Method)
   at java.lang.reflect.Method.invoke(Method.java:372)
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
   Caused by: java.lang.RuntimeException: system server dead?
   at android.appwidget.AppWidgetManager.updateAppWidget(AppWidgetManager.java:651)
   at com.torch2424.simplemonitor.SmAlarm.update(SmAlarm.java:1140)
   at com.torch2424.simplemonitor.SmAlarm.onReceive(SmAlarm.java:1200)
   at android.app.ActivityThread.handleReceiver(ActivityThread.java:2948)
   ... 9 more
   Caused by: android.os.TransactionTooLargeException
   at android.os.BinderProxy.transactNative(Native Method)
   at android.os.BinderProxy.transact(Binder.java:496)
   at com.android.internal.appwidget.IAppWidgetService$Stub$Proxy.updateAppWidgetProvider(IAppWidgetService.java:740)
   at android.appwidget.AppWidgetManager.updateAppWidget(AppWidgetManager.java:648)
   ... 12 more

**Comment by torch2424** [comment]
These seem to be ad and AlarmManager related, and both of these have been updated or removed. closing
